// @flow
export const COLOR_LIKED = 'COLOR_LIKED';
export const LIKED_COLOR_ADDED = 'LIKED_COLOR_ADDED';
export const LIKED_COLORS_ADDED = 'LIKED_COLORS_ADDED';
export const LIKED_COLOR_REMOVED = 'LIKED_COLOR_REMOVED';
export const LIKED_COLOR_CHANGED = 'LIKED_COLOR_CHANGED';

export const COLOR_DISLIKED = 'COLOR_DISLIKED';
export const DISLIKED_COLOR_ADDED = 'DISLIKED_COLOR_ADDED';

export const IS_FETCHING_SET = 'IS_FETCHING_SET';
export const IS_STALE_SET = 'IS_STALE_SET';
export const HAS_FETCH_FAILED_SET = 'HAS_FETCH_FAILED_SET';

export const PALETTE_RECEIVED = 'PALETTE_RECEIVED';
export const PALETTE_REQUESTED = 'PALETTE_REQUESTED';
