export const CONTINUE_ONBOARDING = 'CONTINUE_ONBOARDING';
export const COMPLETE_ONBOARDING = 'COMPLETE_ONBOARDING';

export const ADD_COLOR = 'ADD_COLOR';
export const CHANGE_COLOR = 'CHANGE_COLOR';
export const DISLIKE_COLOR = 'DISLIKE_COLOR';
export const REMOVE_COLOR = 'REMOVE_COLOR';

export const CHANGE_COLOR_TEXT = 'CHANGE_COLOR_TEXT';
export const EDIT_COLOR_TEXT = 'EDIT_COLOR_TEXT';
export const RESET_COLOR_NAME = 'RESET_COLOR_NAME';

export const TOGGLE_COLOR_PICKER = 'TOGGLE_COLOR_PICKER';
export const CLOSE_ALL_COLOR_PICKERS = 'CLOSE_ALL_COLOR_PICKERS';

export const TOGGLE_COLOR_ANIMATION = 'TOGGLE_COLOR_ANIMATION';

export const REQUEST_PALETTE = 'REQUEST_PALETTE';
export const RECEIVE_PALETTE = 'RECEIVE_PALETTE';
export const INVALIDATE_PALETTE = 'INVALIDATE_PALETTE';
