// flow-typed signature: 36e31b1b0d9f11b492eb5e19fc1b88c5
// flow-typed version: <<STUB>>/downloadjs_v^1.4.7/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'downloadjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "downloadjs" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "downloadjs/download" {
  declare module.exports: any;
}

declare module "downloadjs/download.min" {
  declare module.exports: any;
}

// Filename aliases
declare module "downloadjs/download.js" {
  declare module.exports: $Exports<"downloadjs/download">;
}
declare module "downloadjs/download.min.js" {
  declare module.exports: $Exports<"downloadjs/download.min">;
}
