// flow-typed signature: 749afa0046018ba1b3be7b091ad92844
// flow-typed version: <<STUB>>/halogen_v^0.2.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'halogen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "halogen" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "halogen/BeatLoader" {
  declare module.exports: any;
}

declare module "halogen/BounceLoader" {
  declare module.exports: any;
}

declare module "halogen/ClipLoader" {
  declare module.exports: any;
}

declare module "halogen/DotLoader" {
  declare module.exports: any;
}

declare module "halogen/FadeLoader" {
  declare module.exports: any;
}

declare module "halogen/GridLoader" {
  declare module.exports: any;
}

declare module "halogen/Halogen" {
  declare module.exports: any;
}

declare module "halogen/MoonLoader" {
  declare module.exports: any;
}

declare module "halogen/PacmanLoader" {
  declare module.exports: any;
}

declare module "halogen/PulseLoader" {
  declare module.exports: any;
}

declare module "halogen/RingLoader" {
  declare module.exports: any;
}

declare module "halogen/RiseLoader" {
  declare module.exports: any;
}

declare module "halogen/RotateLoader" {
  declare module.exports: any;
}

declare module "halogen/ScaleLoader" {
  declare module.exports: any;
}

declare module "halogen/SkewLoader" {
  declare module.exports: any;
}

declare module "halogen/SquareLoader" {
  declare module.exports: any;
}

declare module "halogen/SyncLoader" {
  declare module.exports: any;
}

// Filename aliases
declare module "halogen/BeatLoader.js" {
  declare module.exports: $Exports<"halogen/BeatLoader">;
}
declare module "halogen/BounceLoader.js" {
  declare module.exports: $Exports<"halogen/BounceLoader">;
}
declare module "halogen/ClipLoader.js" {
  declare module.exports: $Exports<"halogen/ClipLoader">;
}
declare module "halogen/DotLoader.js" {
  declare module.exports: $Exports<"halogen/DotLoader">;
}
declare module "halogen/FadeLoader.js" {
  declare module.exports: $Exports<"halogen/FadeLoader">;
}
declare module "halogen/GridLoader.js" {
  declare module.exports: $Exports<"halogen/GridLoader">;
}
declare module "halogen/Halogen.js" {
  declare module.exports: $Exports<"halogen/Halogen">;
}
declare module "halogen/MoonLoader.js" {
  declare module.exports: $Exports<"halogen/MoonLoader">;
}
declare module "halogen/PacmanLoader.js" {
  declare module.exports: $Exports<"halogen/PacmanLoader">;
}
declare module "halogen/PulseLoader.js" {
  declare module.exports: $Exports<"halogen/PulseLoader">;
}
declare module "halogen/RingLoader.js" {
  declare module.exports: $Exports<"halogen/RingLoader">;
}
declare module "halogen/RiseLoader.js" {
  declare module.exports: $Exports<"halogen/RiseLoader">;
}
declare module "halogen/RotateLoader.js" {
  declare module.exports: $Exports<"halogen/RotateLoader">;
}
declare module "halogen/ScaleLoader.js" {
  declare module.exports: $Exports<"halogen/ScaleLoader">;
}
declare module "halogen/SkewLoader.js" {
  declare module.exports: $Exports<"halogen/SkewLoader">;
}
declare module "halogen/SquareLoader.js" {
  declare module.exports: $Exports<"halogen/SquareLoader">;
}
declare module "halogen/SyncLoader.js" {
  declare module.exports: $Exports<"halogen/SyncLoader">;
}
