// flow-typed signature: 4d7902a07c333b348c826739bd723bc3
// flow-typed version: <<STUB>>/jade_v^1.11.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jade'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "jade" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "jade/bin/jade" {
  declare module.exports: any;
}

declare module "jade/jade" {
  declare module.exports: any;
}

declare module "jade/lib/compiler" {
  declare module.exports: any;
}

declare module "jade/lib/doctypes" {
  declare module.exports: any;
}

declare module "jade/lib/filters-client" {
  declare module.exports: any;
}

declare module "jade/lib/filters" {
  declare module.exports: any;
}

declare module "jade/lib/index" {
  declare module.exports: any;
}

declare module "jade/lib/inline-tags" {
  declare module.exports: any;
}

declare module "jade/lib/lexer" {
  declare module.exports: any;
}

declare module "jade/lib/nodes/attrs" {
  declare module.exports: any;
}

declare module "jade/lib/nodes/block-comment" {
  declare module.exports: any;
}

declare module "jade/lib/nodes/block" {
  declare module.exports: any;
}

declare module "jade/lib/nodes/case" {
  declare module.exports: any;
}

declare module "jade/lib/nodes/code" {
  declare module.exports: any;
}

declare module "jade/lib/nodes/comment" {
  declare module.exports: any;
}

declare module "jade/lib/nodes/doctype" {
  declare module.exports: any;
}

declare module "jade/lib/nodes/each" {
  declare module.exports: any;
}

declare module "jade/lib/nodes/filter" {
  declare module.exports: any;
}

declare module "jade/lib/nodes/index" {
  declare module.exports: any;
}

declare module "jade/lib/nodes/literal" {
  declare module.exports: any;
}

declare module "jade/lib/nodes/mixin-block" {
  declare module.exports: any;
}

declare module "jade/lib/nodes/mixin" {
  declare module.exports: any;
}

declare module "jade/lib/nodes/node" {
  declare module.exports: any;
}

declare module "jade/lib/nodes/tag" {
  declare module.exports: any;
}

declare module "jade/lib/nodes/text" {
  declare module.exports: any;
}

declare module "jade/lib/parser" {
  declare module.exports: any;
}

declare module "jade/lib/runtime" {
  declare module.exports: any;
}

declare module "jade/lib/utils" {
  declare module.exports: any;
}

declare module "jade/release" {
  declare module.exports: any;
}

declare module "jade/runtime" {
  declare module.exports: any;
}

// Filename aliases
declare module "jade/bin/jade.js" {
  declare module.exports: $Exports<"jade/bin/jade">;
}
declare module "jade/jade.js" {
  declare module.exports: $Exports<"jade/jade">;
}
declare module "jade/lib/compiler.js" {
  declare module.exports: $Exports<"jade/lib/compiler">;
}
declare module "jade/lib/doctypes.js" {
  declare module.exports: $Exports<"jade/lib/doctypes">;
}
declare module "jade/lib/filters-client.js" {
  declare module.exports: $Exports<"jade/lib/filters-client">;
}
declare module "jade/lib/filters.js" {
  declare module.exports: $Exports<"jade/lib/filters">;
}
declare module "jade/lib/index.js" {
  declare module.exports: $Exports<"jade/lib/index">;
}
declare module "jade/lib/inline-tags.js" {
  declare module.exports: $Exports<"jade/lib/inline-tags">;
}
declare module "jade/lib/lexer.js" {
  declare module.exports: $Exports<"jade/lib/lexer">;
}
declare module "jade/lib/nodes/attrs.js" {
  declare module.exports: $Exports<"jade/lib/nodes/attrs">;
}
declare module "jade/lib/nodes/block-comment.js" {
  declare module.exports: $Exports<"jade/lib/nodes/block-comment">;
}
declare module "jade/lib/nodes/block.js" {
  declare module.exports: $Exports<"jade/lib/nodes/block">;
}
declare module "jade/lib/nodes/case.js" {
  declare module.exports: $Exports<"jade/lib/nodes/case">;
}
declare module "jade/lib/nodes/code.js" {
  declare module.exports: $Exports<"jade/lib/nodes/code">;
}
declare module "jade/lib/nodes/comment.js" {
  declare module.exports: $Exports<"jade/lib/nodes/comment">;
}
declare module "jade/lib/nodes/doctype.js" {
  declare module.exports: $Exports<"jade/lib/nodes/doctype">;
}
declare module "jade/lib/nodes/each.js" {
  declare module.exports: $Exports<"jade/lib/nodes/each">;
}
declare module "jade/lib/nodes/filter.js" {
  declare module.exports: $Exports<"jade/lib/nodes/filter">;
}
declare module "jade/lib/nodes/index.js" {
  declare module.exports: $Exports<"jade/lib/nodes/index">;
}
declare module "jade/lib/nodes/literal.js" {
  declare module.exports: $Exports<"jade/lib/nodes/literal">;
}
declare module "jade/lib/nodes/mixin-block.js" {
  declare module.exports: $Exports<"jade/lib/nodes/mixin-block">;
}
declare module "jade/lib/nodes/mixin.js" {
  declare module.exports: $Exports<"jade/lib/nodes/mixin">;
}
declare module "jade/lib/nodes/node.js" {
  declare module.exports: $Exports<"jade/lib/nodes/node">;
}
declare module "jade/lib/nodes/tag.js" {
  declare module.exports: $Exports<"jade/lib/nodes/tag">;
}
declare module "jade/lib/nodes/text.js" {
  declare module.exports: $Exports<"jade/lib/nodes/text">;
}
declare module "jade/lib/parser.js" {
  declare module.exports: $Exports<"jade/lib/parser">;
}
declare module "jade/lib/runtime.js" {
  declare module.exports: $Exports<"jade/lib/runtime">;
}
declare module "jade/lib/utils.js" {
  declare module.exports: $Exports<"jade/lib/utils">;
}
declare module "jade/release.js" {
  declare module.exports: $Exports<"jade/release">;
}
declare module "jade/runtime.js" {
  declare module.exports: $Exports<"jade/runtime">;
}
