// flow-typed signature: 44a548c752830e8ee4239b8868da9b6f
// flow-typed version: <<STUB>>/react-css-modules_v^4.6.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-css-modules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-css-modules" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-css-modules/dist/extendReactClass" {
  declare module.exports: any;
}

declare module "react-css-modules/dist/generateAppendClassName" {
  declare module.exports: any;
}

declare module "react-css-modules/dist/index" {
  declare module.exports: any;
}

declare module "react-css-modules/dist/isIterable" {
  declare module.exports: any;
}

declare module "react-css-modules/dist/linkClass" {
  declare module.exports: any;
}

declare module "react-css-modules/dist/makeConfiguration" {
  declare module.exports: any;
}

declare module "react-css-modules/dist/parseStyleName" {
  declare module.exports: any;
}

declare module "react-css-modules/dist/renderNothing" {
  declare module.exports: any;
}

declare module "react-css-modules/dist/SimpleMap" {
  declare module.exports: any;
}

declare module "react-css-modules/dist/wrapStatelessFunction" {
  declare module.exports: any;
}

// Filename aliases
declare module "react-css-modules/dist/extendReactClass.js" {
  declare module.exports: $Exports<"react-css-modules/dist/extendReactClass">;
}
declare module "react-css-modules/dist/generateAppendClassName.js" {
  declare module.exports: $Exports<
    "react-css-modules/dist/generateAppendClassName"
  >;
}
declare module "react-css-modules/dist/index.js" {
  declare module.exports: $Exports<"react-css-modules/dist/index">;
}
declare module "react-css-modules/dist/isIterable.js" {
  declare module.exports: $Exports<"react-css-modules/dist/isIterable">;
}
declare module "react-css-modules/dist/linkClass.js" {
  declare module.exports: $Exports<"react-css-modules/dist/linkClass">;
}
declare module "react-css-modules/dist/makeConfiguration.js" {
  declare module.exports: $Exports<"react-css-modules/dist/makeConfiguration">;
}
declare module "react-css-modules/dist/parseStyleName.js" {
  declare module.exports: $Exports<"react-css-modules/dist/parseStyleName">;
}
declare module "react-css-modules/dist/renderNothing.js" {
  declare module.exports: $Exports<"react-css-modules/dist/renderNothing">;
}
declare module "react-css-modules/dist/SimpleMap.js" {
  declare module.exports: $Exports<"react-css-modules/dist/SimpleMap">;
}
declare module "react-css-modules/dist/wrapStatelessFunction.js" {
  declare module.exports: $Exports<
    "react-css-modules/dist/wrapStatelessFunction"
  >;
}
