// flow-typed signature: 5e5d64eaaebc77b47f78b56ef0d2a8d1
// flow-typed version: <<STUB>>/react-copy-to-clipboard_v^5.0.1/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-copy-to-clipboard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-copy-to-clipboard" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-copy-to-clipboard/build/react-copy-to-clipboard" {
  declare module.exports: any;
}

declare module "react-copy-to-clipboard/build/react-copy-to-clipboard.min" {
  declare module.exports: any;
}

declare module "react-copy-to-clipboard/lib/Component" {
  declare module.exports: any;
}

declare module "react-copy-to-clipboard/lib/index" {
  declare module.exports: any;
}

declare module "react-copy-to-clipboard/src/Component" {
  declare module.exports: any;
}

declare module "react-copy-to-clipboard/src/index" {
  declare module.exports: any;
}

// Filename aliases
declare module "react-copy-to-clipboard/build/react-copy-to-clipboard.js" {
  declare module.exports: $Exports<
    "react-copy-to-clipboard/build/react-copy-to-clipboard"
  >;
}
declare module "react-copy-to-clipboard/build/react-copy-to-clipboard.min.js" {
  declare module.exports: $Exports<
    "react-copy-to-clipboard/build/react-copy-to-clipboard.min"
  >;
}
declare module "react-copy-to-clipboard/lib/Component.js" {
  declare module.exports: $Exports<"react-copy-to-clipboard/lib/Component">;
}
declare module "react-copy-to-clipboard/lib/index.js" {
  declare module.exports: $Exports<"react-copy-to-clipboard/lib/index">;
}
declare module "react-copy-to-clipboard/src/Component.js" {
  declare module.exports: $Exports<"react-copy-to-clipboard/src/Component">;
}
declare module "react-copy-to-clipboard/src/index.js" {
  declare module.exports: $Exports<"react-copy-to-clipboard/src/index">;
}
