// flow-typed signature: 89a8b135d8d0898c35d44021428cb9bf
// flow-typed version: <<STUB>>/react-color_v^2.1.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-color'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-color" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-color/lib/components/alpha/Alpha" {
  declare module.exports: any;
}

declare module "react-color/lib/components/alpha/AlphaPointer" {
  declare module.exports: any;
}

declare module "react-color/lib/components/alpha/spec" {
  declare module.exports: any;
}

declare module "react-color/lib/components/block/Block" {
  declare module.exports: any;
}

declare module "react-color/lib/components/block/BlockSwatches" {
  declare module.exports: any;
}

declare module "react-color/lib/components/block/spec" {
  declare module.exports: any;
}

declare module "react-color/lib/components/block/story" {
  declare module.exports: any;
}

declare module "react-color/lib/components/chrome/Chrome" {
  declare module.exports: any;
}

declare module "react-color/lib/components/chrome/ChromeFields" {
  declare module.exports: any;
}

declare module "react-color/lib/components/chrome/ChromePointer" {
  declare module.exports: any;
}

declare module "react-color/lib/components/chrome/ChromePointerCircle" {
  declare module.exports: any;
}

declare module "react-color/lib/components/chrome/spec" {
  declare module.exports: any;
}

declare module "react-color/lib/components/chrome/story" {
  declare module.exports: any;
}

declare module "react-color/lib/components/circle/Circle" {
  declare module.exports: any;
}

declare module "react-color/lib/components/circle/CircleSwatch" {
  declare module.exports: any;
}

declare module "react-color/lib/components/circle/spec" {
  declare module.exports: any;
}

declare module "react-color/lib/components/circle/story" {
  declare module.exports: any;
}

declare module "react-color/lib/components/common/Alpha" {
  declare module.exports: any;
}

declare module "react-color/lib/components/common/Checkboard" {
  declare module.exports: any;
}

declare module "react-color/lib/components/common/ColorWrap" {
  declare module.exports: any;
}

declare module "react-color/lib/components/common/EditableInput" {
  declare module.exports: any;
}

declare module "react-color/lib/components/common/Hue" {
  declare module.exports: any;
}

declare module "react-color/lib/components/common/index" {
  declare module.exports: any;
}

declare module "react-color/lib/components/common/Raised" {
  declare module.exports: any;
}

declare module "react-color/lib/components/common/Saturation" {
  declare module.exports: any;
}

declare module "react-color/lib/components/common/spec" {
  declare module.exports: any;
}

declare module "react-color/lib/components/common/Swatch" {
  declare module.exports: any;
}

declare module "react-color/lib/components/compact/Compact" {
  declare module.exports: any;
}

declare module "react-color/lib/components/compact/CompactColor" {
  declare module.exports: any;
}

declare module "react-color/lib/components/compact/CompactFields" {
  declare module.exports: any;
}

declare module "react-color/lib/components/compact/spec" {
  declare module.exports: any;
}

declare module "react-color/lib/components/compact/story" {
  declare module.exports: any;
}

declare module "react-color/lib/components/github/Github" {
  declare module.exports: any;
}

declare module "react-color/lib/components/github/GithubSwatch" {
  declare module.exports: any;
}

declare module "react-color/lib/components/github/spec" {
  declare module.exports: any;
}

declare module "react-color/lib/components/github/story" {
  declare module.exports: any;
}

declare module "react-color/lib/components/hue/Hue" {
  declare module.exports: any;
}

declare module "react-color/lib/components/hue/HuePointer" {
  declare module.exports: any;
}

declare module "react-color/lib/components/hue/spec" {
  declare module.exports: any;
}

declare module "react-color/lib/components/material/Material" {
  declare module.exports: any;
}

declare module "react-color/lib/components/material/spec" {
  declare module.exports: any;
}

declare module "react-color/lib/components/material/story" {
  declare module.exports: any;
}

declare module "react-color/lib/components/photoshop/Photoshop" {
  declare module.exports: any;
}

declare module "react-color/lib/components/photoshop/PhotoshopButton" {
  declare module.exports: any;
}

declare module "react-color/lib/components/photoshop/PhotoshopFields" {
  declare module.exports: any;
}

declare module "react-color/lib/components/photoshop/PhotoshopPointer" {
  declare module.exports: any;
}

declare module "react-color/lib/components/photoshop/PhotoshopPointerCircle" {
  declare module.exports: any;
}

declare module "react-color/lib/components/photoshop/PhotoshopPreviews" {
  declare module.exports: any;
}

declare module "react-color/lib/components/photoshop/spec" {
  declare module.exports: any;
}

declare module "react-color/lib/components/photoshop/story" {
  declare module.exports: any;
}

declare module "react-color/lib/components/sketch/Sketch" {
  declare module.exports: any;
}

declare module "react-color/lib/components/sketch/SketchFields" {
  declare module.exports: any;
}

declare module "react-color/lib/components/sketch/SketchPresetColors" {
  declare module.exports: any;
}

declare module "react-color/lib/components/sketch/spec" {
  declare module.exports: any;
}

declare module "react-color/lib/components/sketch/story" {
  declare module.exports: any;
}

declare module "react-color/lib/components/slider/Slider" {
  declare module.exports: any;
}

declare module "react-color/lib/components/slider/SliderPointer" {
  declare module.exports: any;
}

declare module "react-color/lib/components/slider/SliderSwatch" {
  declare module.exports: any;
}

declare module "react-color/lib/components/slider/SliderSwatches" {
  declare module.exports: any;
}

declare module "react-color/lib/components/slider/spec" {
  declare module.exports: any;
}

declare module "react-color/lib/components/swatches/spec" {
  declare module.exports: any;
}

declare module "react-color/lib/components/swatches/story" {
  declare module.exports: any;
}

declare module "react-color/lib/components/swatches/Swatches" {
  declare module.exports: any;
}

declare module "react-color/lib/components/swatches/SwatchesColor" {
  declare module.exports: any;
}

declare module "react-color/lib/components/swatches/SwatchesGroup" {
  declare module.exports: any;
}

declare module "react-color/lib/components/twitter/spec" {
  declare module.exports: any;
}

declare module "react-color/lib/components/twitter/story" {
  declare module.exports: any;
}

declare module "react-color/lib/components/twitter/Twitter" {
  declare module.exports: any;
}

declare module "react-color/lib/helpers/alpha" {
  declare module.exports: any;
}

declare module "react-color/lib/helpers/checkboard" {
  declare module.exports: any;
}

declare module "react-color/lib/helpers/color" {
  declare module.exports: any;
}

declare module "react-color/lib/helpers/hue" {
  declare module.exports: any;
}

declare module "react-color/lib/helpers/interaction" {
  declare module.exports: any;
}

declare module "react-color/lib/helpers/saturation" {
  declare module.exports: any;
}

declare module "react-color/lib/helpers/spec" {
  declare module.exports: any;
}

declare module "react-color/lib/index" {
  declare module.exports: any;
}

declare module "react-color/scripts/docs-dist" {
  declare module.exports: any;
}

declare module "react-color/scripts/docs-server" {
  declare module.exports: any;
}

declare module "react-color/webpack.config" {
  declare module.exports: any;
}

// Filename aliases
declare module "react-color/lib/components/alpha/Alpha.js" {
  declare module.exports: $Exports<"react-color/lib/components/alpha/Alpha">;
}
declare module "react-color/lib/components/alpha/AlphaPointer.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/alpha/AlphaPointer"
  >;
}
declare module "react-color/lib/components/alpha/spec.js" {
  declare module.exports: $Exports<"react-color/lib/components/alpha/spec">;
}
declare module "react-color/lib/components/block/Block.js" {
  declare module.exports: $Exports<"react-color/lib/components/block/Block">;
}
declare module "react-color/lib/components/block/BlockSwatches.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/block/BlockSwatches"
  >;
}
declare module "react-color/lib/components/block/spec.js" {
  declare module.exports: $Exports<"react-color/lib/components/block/spec">;
}
declare module "react-color/lib/components/block/story.js" {
  declare module.exports: $Exports<"react-color/lib/components/block/story">;
}
declare module "react-color/lib/components/chrome/Chrome.js" {
  declare module.exports: $Exports<"react-color/lib/components/chrome/Chrome">;
}
declare module "react-color/lib/components/chrome/ChromeFields.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/chrome/ChromeFields"
  >;
}
declare module "react-color/lib/components/chrome/ChromePointer.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/chrome/ChromePointer"
  >;
}
declare module "react-color/lib/components/chrome/ChromePointerCircle.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/chrome/ChromePointerCircle"
  >;
}
declare module "react-color/lib/components/chrome/spec.js" {
  declare module.exports: $Exports<"react-color/lib/components/chrome/spec">;
}
declare module "react-color/lib/components/chrome/story.js" {
  declare module.exports: $Exports<"react-color/lib/components/chrome/story">;
}
declare module "react-color/lib/components/circle/Circle.js" {
  declare module.exports: $Exports<"react-color/lib/components/circle/Circle">;
}
declare module "react-color/lib/components/circle/CircleSwatch.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/circle/CircleSwatch"
  >;
}
declare module "react-color/lib/components/circle/spec.js" {
  declare module.exports: $Exports<"react-color/lib/components/circle/spec">;
}
declare module "react-color/lib/components/circle/story.js" {
  declare module.exports: $Exports<"react-color/lib/components/circle/story">;
}
declare module "react-color/lib/components/common/Alpha.js" {
  declare module.exports: $Exports<"react-color/lib/components/common/Alpha">;
}
declare module "react-color/lib/components/common/Checkboard.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/common/Checkboard"
  >;
}
declare module "react-color/lib/components/common/ColorWrap.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/common/ColorWrap"
  >;
}
declare module "react-color/lib/components/common/EditableInput.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/common/EditableInput"
  >;
}
declare module "react-color/lib/components/common/Hue.js" {
  declare module.exports: $Exports<"react-color/lib/components/common/Hue">;
}
declare module "react-color/lib/components/common/index.js" {
  declare module.exports: $Exports<"react-color/lib/components/common/index">;
}
declare module "react-color/lib/components/common/Raised.js" {
  declare module.exports: $Exports<"react-color/lib/components/common/Raised">;
}
declare module "react-color/lib/components/common/Saturation.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/common/Saturation"
  >;
}
declare module "react-color/lib/components/common/spec.js" {
  declare module.exports: $Exports<"react-color/lib/components/common/spec">;
}
declare module "react-color/lib/components/common/Swatch.js" {
  declare module.exports: $Exports<"react-color/lib/components/common/Swatch">;
}
declare module "react-color/lib/components/compact/Compact.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/compact/Compact"
  >;
}
declare module "react-color/lib/components/compact/CompactColor.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/compact/CompactColor"
  >;
}
declare module "react-color/lib/components/compact/CompactFields.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/compact/CompactFields"
  >;
}
declare module "react-color/lib/components/compact/spec.js" {
  declare module.exports: $Exports<"react-color/lib/components/compact/spec">;
}
declare module "react-color/lib/components/compact/story.js" {
  declare module.exports: $Exports<"react-color/lib/components/compact/story">;
}
declare module "react-color/lib/components/github/Github.js" {
  declare module.exports: $Exports<"react-color/lib/components/github/Github">;
}
declare module "react-color/lib/components/github/GithubSwatch.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/github/GithubSwatch"
  >;
}
declare module "react-color/lib/components/github/spec.js" {
  declare module.exports: $Exports<"react-color/lib/components/github/spec">;
}
declare module "react-color/lib/components/github/story.js" {
  declare module.exports: $Exports<"react-color/lib/components/github/story">;
}
declare module "react-color/lib/components/hue/Hue.js" {
  declare module.exports: $Exports<"react-color/lib/components/hue/Hue">;
}
declare module "react-color/lib/components/hue/HuePointer.js" {
  declare module.exports: $Exports<"react-color/lib/components/hue/HuePointer">;
}
declare module "react-color/lib/components/hue/spec.js" {
  declare module.exports: $Exports<"react-color/lib/components/hue/spec">;
}
declare module "react-color/lib/components/material/Material.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/material/Material"
  >;
}
declare module "react-color/lib/components/material/spec.js" {
  declare module.exports: $Exports<"react-color/lib/components/material/spec">;
}
declare module "react-color/lib/components/material/story.js" {
  declare module.exports: $Exports<"react-color/lib/components/material/story">;
}
declare module "react-color/lib/components/photoshop/Photoshop.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/photoshop/Photoshop"
  >;
}
declare module "react-color/lib/components/photoshop/PhotoshopButton.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/photoshop/PhotoshopButton"
  >;
}
declare module "react-color/lib/components/photoshop/PhotoshopFields.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/photoshop/PhotoshopFields"
  >;
}
declare module "react-color/lib/components/photoshop/PhotoshopPointer.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/photoshop/PhotoshopPointer"
  >;
}
declare module "react-color/lib/components/photoshop/PhotoshopPointerCircle.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/photoshop/PhotoshopPointerCircle"
  >;
}
declare module "react-color/lib/components/photoshop/PhotoshopPreviews.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/photoshop/PhotoshopPreviews"
  >;
}
declare module "react-color/lib/components/photoshop/spec.js" {
  declare module.exports: $Exports<"react-color/lib/components/photoshop/spec">;
}
declare module "react-color/lib/components/photoshop/story.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/photoshop/story"
  >;
}
declare module "react-color/lib/components/sketch/Sketch.js" {
  declare module.exports: $Exports<"react-color/lib/components/sketch/Sketch">;
}
declare module "react-color/lib/components/sketch/SketchFields.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/sketch/SketchFields"
  >;
}
declare module "react-color/lib/components/sketch/SketchPresetColors.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/sketch/SketchPresetColors"
  >;
}
declare module "react-color/lib/components/sketch/spec.js" {
  declare module.exports: $Exports<"react-color/lib/components/sketch/spec">;
}
declare module "react-color/lib/components/sketch/story.js" {
  declare module.exports: $Exports<"react-color/lib/components/sketch/story">;
}
declare module "react-color/lib/components/slider/Slider.js" {
  declare module.exports: $Exports<"react-color/lib/components/slider/Slider">;
}
declare module "react-color/lib/components/slider/SliderPointer.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/slider/SliderPointer"
  >;
}
declare module "react-color/lib/components/slider/SliderSwatch.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/slider/SliderSwatch"
  >;
}
declare module "react-color/lib/components/slider/SliderSwatches.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/slider/SliderSwatches"
  >;
}
declare module "react-color/lib/components/slider/spec.js" {
  declare module.exports: $Exports<"react-color/lib/components/slider/spec">;
}
declare module "react-color/lib/components/swatches/spec.js" {
  declare module.exports: $Exports<"react-color/lib/components/swatches/spec">;
}
declare module "react-color/lib/components/swatches/story.js" {
  declare module.exports: $Exports<"react-color/lib/components/swatches/story">;
}
declare module "react-color/lib/components/swatches/Swatches.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/swatches/Swatches"
  >;
}
declare module "react-color/lib/components/swatches/SwatchesColor.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/swatches/SwatchesColor"
  >;
}
declare module "react-color/lib/components/swatches/SwatchesGroup.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/swatches/SwatchesGroup"
  >;
}
declare module "react-color/lib/components/twitter/spec.js" {
  declare module.exports: $Exports<"react-color/lib/components/twitter/spec">;
}
declare module "react-color/lib/components/twitter/story.js" {
  declare module.exports: $Exports<"react-color/lib/components/twitter/story">;
}
declare module "react-color/lib/components/twitter/Twitter.js" {
  declare module.exports: $Exports<
    "react-color/lib/components/twitter/Twitter"
  >;
}
declare module "react-color/lib/helpers/alpha.js" {
  declare module.exports: $Exports<"react-color/lib/helpers/alpha">;
}
declare module "react-color/lib/helpers/checkboard.js" {
  declare module.exports: $Exports<"react-color/lib/helpers/checkboard">;
}
declare module "react-color/lib/helpers/color.js" {
  declare module.exports: $Exports<"react-color/lib/helpers/color">;
}
declare module "react-color/lib/helpers/hue.js" {
  declare module.exports: $Exports<"react-color/lib/helpers/hue">;
}
declare module "react-color/lib/helpers/interaction.js" {
  declare module.exports: $Exports<"react-color/lib/helpers/interaction">;
}
declare module "react-color/lib/helpers/saturation.js" {
  declare module.exports: $Exports<"react-color/lib/helpers/saturation">;
}
declare module "react-color/lib/helpers/spec.js" {
  declare module.exports: $Exports<"react-color/lib/helpers/spec">;
}
declare module "react-color/lib/index.js" {
  declare module.exports: $Exports<"react-color/lib/index">;
}
declare module "react-color/scripts/docs-dist.js" {
  declare module.exports: $Exports<"react-color/scripts/docs-dist">;
}
declare module "react-color/scripts/docs-server.js" {
  declare module.exports: $Exports<"react-color/scripts/docs-server">;
}
declare module "react-color/webpack.config.js" {
  declare module.exports: $Exports<"react-color/webpack.config">;
}
