// flow-typed signature: 2f9ffb2f4a3b5b36d2b56e2ba50988c0
// flow-typed version: <<STUB>>/resolve_v1.6.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'resolve'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'resolve' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'resolve/example/async' {
  declare module.exports: any;
}

declare module 'resolve/example/sync' {
  declare module.exports: any;
}

declare module 'resolve/lib/async' {
  declare module.exports: any;
}

declare module 'resolve/lib/caller' {
  declare module.exports: any;
}

declare module 'resolve/lib/core' {
  declare module.exports: any;
}

declare module 'resolve/lib/node-modules-paths' {
  declare module.exports: any;
}

declare module 'resolve/lib/sync' {
  declare module.exports: any;
}

declare module 'resolve/test/core' {
  declare module.exports: any;
}

declare module 'resolve/test/dotdot' {
  declare module.exports: any;
}

declare module 'resolve/test/dotdot/abc/index' {
  declare module.exports: any;
}

declare module 'resolve/test/dotdot/index' {
  declare module.exports: any;
}

declare module 'resolve/test/faulty_basedir' {
  declare module.exports: any;
}

declare module 'resolve/test/filter_sync' {
  declare module.exports: any;
}

declare module 'resolve/test/filter' {
  declare module.exports: any;
}

declare module 'resolve/test/mock_sync' {
  declare module.exports: any;
}

declare module 'resolve/test/mock' {
  declare module.exports: any;
}

declare module 'resolve/test/module_dir' {
  declare module.exports: any;
}

declare module 'resolve/test/module_dir/xmodules/aaa/index' {
  declare module.exports: any;
}

declare module 'resolve/test/module_dir/ymodules/aaa/index' {
  declare module.exports: any;
}

declare module 'resolve/test/module_dir/zmodules/bbb/main' {
  declare module.exports: any;
}

declare module 'resolve/test/node_path' {
  declare module.exports: any;
}

declare module 'resolve/test/node_path/x/aaa/index' {
  declare module.exports: any;
}

declare module 'resolve/test/node_path/x/ccc/index' {
  declare module.exports: any;
}

declare module 'resolve/test/node_path/y/bbb/index' {
  declare module.exports: any;
}

declare module 'resolve/test/node_path/y/ccc/index' {
  declare module.exports: any;
}

declare module 'resolve/test/node-modules-paths' {
  declare module.exports: any;
}

declare module 'resolve/test/nonstring' {
  declare module.exports: any;
}

declare module 'resolve/test/pathfilter' {
  declare module.exports: any;
}

declare module 'resolve/test/pathfilter/deep_ref/main' {
  declare module.exports: any;
}

declare module 'resolve/test/precedence' {
  declare module.exports: any;
}

declare module 'resolve/test/precedence/aaa' {
  declare module.exports: any;
}

declare module 'resolve/test/precedence/aaa/index' {
  declare module.exports: any;
}

declare module 'resolve/test/precedence/aaa/main' {
  declare module.exports: any;
}

declare module 'resolve/test/precedence/bbb' {
  declare module.exports: any;
}

declare module 'resolve/test/precedence/bbb/main' {
  declare module.exports: any;
}

declare module 'resolve/test/resolver_sync' {
  declare module.exports: any;
}

declare module 'resolve/test/resolver' {
  declare module.exports: any;
}

declare module 'resolve/test/resolver/baz/doom' {
  declare module.exports: any;
}

declare module 'resolve/test/resolver/baz/quux' {
  declare module.exports: any;
}

declare module 'resolve/test/resolver/dot_main/index' {
  declare module.exports: any;
}

declare module 'resolve/test/resolver/dot_slash_main/index' {
  declare module.exports: any;
}

declare module 'resolve/test/resolver/foo' {
  declare module.exports: any;
}

declare module 'resolve/test/resolver/incorrect_main/index' {
  declare module.exports: any;
}

declare module 'resolve/test/resolver/mug' {
  declare module.exports: any;
}

declare module 'resolve/test/resolver/other_path/lib/other-lib' {
  declare module.exports: any;
}

declare module 'resolve/test/resolver/other_path/root' {
  declare module.exports: any;
}

declare module 'resolve/test/resolver/quux/foo/index' {
  declare module.exports: any;
}

declare module 'resolve/test/resolver/same_names/foo' {
  declare module.exports: any;
}

declare module 'resolve/test/resolver/same_names/foo/index' {
  declare module.exports: any;
}

declare module 'resolve/test/resolver/symlinked/_/node_modules/foo' {
  declare module.exports: any;
}

declare module 'resolve/test/resolver/without_basedir/main' {
  declare module.exports: any;
}

declare module 'resolve/test/subdirs' {
  declare module.exports: any;
}

declare module 'resolve/test/symlinks' {
  declare module.exports: any;
}

// Filename aliases
declare module 'resolve/example/async.js' {
  declare module.exports: $Exports<'resolve/example/async'>;
}
declare module 'resolve/example/sync.js' {
  declare module.exports: $Exports<'resolve/example/sync'>;
}
declare module 'resolve/index' {
  declare module.exports: $Exports<'resolve'>;
}
declare module 'resolve/index.js' {
  declare module.exports: $Exports<'resolve'>;
}
declare module 'resolve/lib/async.js' {
  declare module.exports: $Exports<'resolve/lib/async'>;
}
declare module 'resolve/lib/caller.js' {
  declare module.exports: $Exports<'resolve/lib/caller'>;
}
declare module 'resolve/lib/core.js' {
  declare module.exports: $Exports<'resolve/lib/core'>;
}
declare module 'resolve/lib/node-modules-paths.js' {
  declare module.exports: $Exports<'resolve/lib/node-modules-paths'>;
}
declare module 'resolve/lib/sync.js' {
  declare module.exports: $Exports<'resolve/lib/sync'>;
}
declare module 'resolve/test/core.js' {
  declare module.exports: $Exports<'resolve/test/core'>;
}
declare module 'resolve/test/dotdot.js' {
  declare module.exports: $Exports<'resolve/test/dotdot'>;
}
declare module 'resolve/test/dotdot/abc/index.js' {
  declare module.exports: $Exports<'resolve/test/dotdot/abc/index'>;
}
declare module 'resolve/test/dotdot/index.js' {
  declare module.exports: $Exports<'resolve/test/dotdot/index'>;
}
declare module 'resolve/test/faulty_basedir.js' {
  declare module.exports: $Exports<'resolve/test/faulty_basedir'>;
}
declare module 'resolve/test/filter_sync.js' {
  declare module.exports: $Exports<'resolve/test/filter_sync'>;
}
declare module 'resolve/test/filter.js' {
  declare module.exports: $Exports<'resolve/test/filter'>;
}
declare module 'resolve/test/mock_sync.js' {
  declare module.exports: $Exports<'resolve/test/mock_sync'>;
}
declare module 'resolve/test/mock.js' {
  declare module.exports: $Exports<'resolve/test/mock'>;
}
declare module 'resolve/test/module_dir.js' {
  declare module.exports: $Exports<'resolve/test/module_dir'>;
}
declare module 'resolve/test/module_dir/xmodules/aaa/index.js' {
  declare module.exports: $Exports<
    'resolve/test/module_dir/xmodules/aaa/index'
  >;
}
declare module 'resolve/test/module_dir/ymodules/aaa/index.js' {
  declare module.exports: $Exports<
    'resolve/test/module_dir/ymodules/aaa/index'
  >;
}
declare module 'resolve/test/module_dir/zmodules/bbb/main.js' {
  declare module.exports: $Exports<'resolve/test/module_dir/zmodules/bbb/main'>;
}
declare module 'resolve/test/node_path.js' {
  declare module.exports: $Exports<'resolve/test/node_path'>;
}
declare module 'resolve/test/node_path/x/aaa/index.js' {
  declare module.exports: $Exports<'resolve/test/node_path/x/aaa/index'>;
}
declare module 'resolve/test/node_path/x/ccc/index.js' {
  declare module.exports: $Exports<'resolve/test/node_path/x/ccc/index'>;
}
declare module 'resolve/test/node_path/y/bbb/index.js' {
  declare module.exports: $Exports<'resolve/test/node_path/y/bbb/index'>;
}
declare module 'resolve/test/node_path/y/ccc/index.js' {
  declare module.exports: $Exports<'resolve/test/node_path/y/ccc/index'>;
}
declare module 'resolve/test/node-modules-paths.js' {
  declare module.exports: $Exports<'resolve/test/node-modules-paths'>;
}
declare module 'resolve/test/nonstring.js' {
  declare module.exports: $Exports<'resolve/test/nonstring'>;
}
declare module 'resolve/test/pathfilter.js' {
  declare module.exports: $Exports<'resolve/test/pathfilter'>;
}
declare module 'resolve/test/pathfilter/deep_ref/main.js' {
  declare module.exports: $Exports<'resolve/test/pathfilter/deep_ref/main'>;
}
declare module 'resolve/test/precedence.js' {
  declare module.exports: $Exports<'resolve/test/precedence'>;
}
declare module 'resolve/test/precedence/aaa.js' {
  declare module.exports: $Exports<'resolve/test/precedence/aaa'>;
}
declare module 'resolve/test/precedence/aaa/index.js' {
  declare module.exports: $Exports<'resolve/test/precedence/aaa/index'>;
}
declare module 'resolve/test/precedence/aaa/main.js' {
  declare module.exports: $Exports<'resolve/test/precedence/aaa/main'>;
}
declare module 'resolve/test/precedence/bbb.js' {
  declare module.exports: $Exports<'resolve/test/precedence/bbb'>;
}
declare module 'resolve/test/precedence/bbb/main.js' {
  declare module.exports: $Exports<'resolve/test/precedence/bbb/main'>;
}
declare module 'resolve/test/resolver_sync.js' {
  declare module.exports: $Exports<'resolve/test/resolver_sync'>;
}
declare module 'resolve/test/resolver.js' {
  declare module.exports: $Exports<'resolve/test/resolver'>;
}
declare module 'resolve/test/resolver/baz/doom.js' {
  declare module.exports: $Exports<'resolve/test/resolver/baz/doom'>;
}
declare module 'resolve/test/resolver/baz/quux.js' {
  declare module.exports: $Exports<'resolve/test/resolver/baz/quux'>;
}
declare module 'resolve/test/resolver/dot_main/index.js' {
  declare module.exports: $Exports<'resolve/test/resolver/dot_main/index'>;
}
declare module 'resolve/test/resolver/dot_slash_main/index.js' {
  declare module.exports: $Exports<
    'resolve/test/resolver/dot_slash_main/index'
  >;
}
declare module 'resolve/test/resolver/foo.js' {
  declare module.exports: $Exports<'resolve/test/resolver/foo'>;
}
declare module 'resolve/test/resolver/incorrect_main/index.js' {
  declare module.exports: $Exports<
    'resolve/test/resolver/incorrect_main/index'
  >;
}
declare module 'resolve/test/resolver/mug.js' {
  declare module.exports: $Exports<'resolve/test/resolver/mug'>;
}
declare module 'resolve/test/resolver/other_path/lib/other-lib.js' {
  declare module.exports: $Exports<
    'resolve/test/resolver/other_path/lib/other-lib'
  >;
}
declare module 'resolve/test/resolver/other_path/root.js' {
  declare module.exports: $Exports<'resolve/test/resolver/other_path/root'>;
}
declare module 'resolve/test/resolver/quux/foo/index.js' {
  declare module.exports: $Exports<'resolve/test/resolver/quux/foo/index'>;
}
declare module 'resolve/test/resolver/same_names/foo.js' {
  declare module.exports: $Exports<'resolve/test/resolver/same_names/foo'>;
}
declare module 'resolve/test/resolver/same_names/foo/index.js' {
  declare module.exports: $Exports<
    'resolve/test/resolver/same_names/foo/index'
  >;
}
declare module 'resolve/test/resolver/symlinked/_/node_modules/foo.js' {
  declare module.exports: $Exports<
    'resolve/test/resolver/symlinked/_/node_modules/foo'
  >;
}
declare module 'resolve/test/resolver/without_basedir/main.js' {
  declare module.exports: $Exports<
    'resolve/test/resolver/without_basedir/main'
  >;
}
declare module 'resolve/test/subdirs.js' {
  declare module.exports: $Exports<'resolve/test/subdirs'>;
}
declare module 'resolve/test/symlinks.js' {
  declare module.exports: $Exports<'resolve/test/symlinks'>;
}
