// flow-typed signature: 1cf5b549bcf267971a707ff37a6aef82
// flow-typed version: <<STUB>>/svg-inline-react_v^2.1.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'svg-inline-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "svg-inline-react" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "svg-inline-react/dist/index" {
  declare module.exports: any;
}

declare module "svg-inline-react/karma.conf" {
  declare module.exports: any;
}

declare module "svg-inline-react/lib/index" {
  declare module.exports: any;
}

declare module "svg-inline-react/lib/util" {
  declare module.exports: any;
}

declare module "svg-inline-react/webpack.config" {
  declare module.exports: any;
}

// Filename aliases
declare module "svg-inline-react/dist/index.js" {
  declare module.exports: $Exports<"svg-inline-react/dist/index">;
}
declare module "svg-inline-react/karma.conf.js" {
  declare module.exports: $Exports<"svg-inline-react/karma.conf">;
}
declare module "svg-inline-react/lib/index.js" {
  declare module.exports: $Exports<"svg-inline-react/lib/index">;
}
declare module "svg-inline-react/lib/util.js" {
  declare module.exports: $Exports<"svg-inline-react/lib/util">;
}
declare module "svg-inline-react/webpack.config.js" {
  declare module.exports: $Exports<"svg-inline-react/webpack.config">;
}
