// flow-typed signature: 9e5b699c1442fbf18b0e35c9db9e2bcd
// flow-typed version: <<STUB>>/whatwg-fetch_v2.0.3/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'whatwg-fetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "whatwg-fetch" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "whatwg-fetch/fetch" {
  declare module.exports: any;
}

// Filename aliases
declare module "whatwg-fetch/fetch.js" {
  declare module.exports: $Exports<"whatwg-fetch/fetch">;
}
